# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20171011_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporters',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
