# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 00:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20171011_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporters',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
